### ISSUE TITLE
publish latest version on npm

### ISSUE THREAD

**Issue by MartijnR** [aaronpowell/db.js#170]
I look forward to including the modernized version of db.js. :+1: 

:shipit:

**Comment by aaronpowell** [comment]
ah, I need to automate that process :grimacing:

**Comment by aaronpowell** [comment]
Ok, I've published 0.13.2 to npm. There'll be a new build soon, once I've had time to look at @brettz9's latest PR (back at the day job, makes my time to look diminish :stuck_out_tongue: )

**Comment by MartijnR** [comment]
Thanks! Yes automating would be nice whenever package.json version updates. I should figure that out too.

**Comment by aaronpowell** [comment]
I just did b1d15244d272b17f75939d17103e06a6baaa8516 which now shows the npm version in the readme, which should help me remember to publish :wink:

**Comment by brettz9** [comment]
Btw, as far as Saucelabs, even the [latest Travis build](https://github.com/aaronpowell/db.js/pull/141), while passing, is still showing,

    Unable to load saucelabs key

    >> Local Npm module "grunt-cli" not found. Is it installed?"

Is that something you're aware of?

**Comment by aaronpowell** [comment]
@brettz9 I think you're mistaken. Here's the latest build - https://travis-ci.org/aaronpowell/db.js/builds/114686376

That one hit Sauce Labs correctly. Pull Requests from external repositories don't have access to secure config values (see: https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests) so I detect if it's a PR and skip calling Sauce Labs anyway. The warning in the logs can probably be disabled for the PR builds too, but I find it useful for testing to remind me to set the key.

**Comment by brettz9** [comment]
Ah, gotcha, cool, thanks!

**Comment by brettz9** [comment]
I noticed it still says `>> Local Npm module "grunt-cli" not found. Is it installed?`. Any idea why that would be?

**Comment by aaronpowell** [comment]
I think it's because the `Gruntfile` does a scan for all dependencies matching `grunt-*` and `grunt-cli` is there but it's not something you can use `require` with. I should improve the filter to get rid of the warning.

It came about when I removed the requirement to have globally installed node modules to run.

**Comment by brettz9** [comment]
I see the message was solved in at least one case by putting it in `peerDependencies` and I do see discussion that this is meant for plug-ins, such as for Grunt, where there is no `require` use.
